AllCops:
  Exclude:
    - 'bench/**/*'
    - 'bin/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Style/IfUnlessModifier:
  Enabled: false

# Documentation is coming
Style/Documentation:
  Enabled: false

# Extend self preserves private methods
Style/ModuleFunction:
  Enabled: false

Style/PredicateName:
  NamePrefix:
    - is_
  NamePrefixBlacklist:
    - is_

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Style/IndentArray:
  Enabled: false
