AllCops:
  Exclude:
    - "bench/**/*"
    - "bin/*"
    - "tmp/**/*"
    - "vendor/**/*"
  TargetRubyVersion: 2.3

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Exclude:
    - "Gemfile*"
    - "Rakefile"
    - "*.gemspec"
    - "spec/**/*"

Style/IfUnlessModifier:
  Enabled: false

Style/Documentation:
  Enabled: true

# Extend self preserves private methods
Style/ModuleFunction:
  Enabled: false

Style/PredicateName:
  NamePrefix:
    - is_
  NamePrefixBlacklist:
    - is_

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Style/IndentArray:
  Enabled: false
